version: '3'

services:
  bot:
    image: bot:0.1
    build: ./
#     ports:
#       - "5000:5000"
#      volumes:
#       - ./*:$HOME/bot
    environment:
      - REDIS_ENDPOINT=redis://redis:6379/

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

#  mempool:
#    ? download and run turbogeth txpool

