version: "3"

services:
  bot:
    image: liujjw/bot:0.1
    environment:
      - REDIS_ENDPOINT=redis://redis:6379/
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PROVIDER_ENDPOINT=mempool://mempool:8547/
      - RUNNER_ENDPOINT=http://localhost:8080
      - RUNNER_PORT=8080
      - NODE_ENV=staging
      - IPC_PROVIDER_ENDPOINT=/d/ethereum/.ethereum/geth.ipc
      - WS_PROVIDER_ENDPOINT=ws://localhost:8546
      - DB_NUMBER_FOR_JOBS=15
      - DB_NUMBER_FOR_DATA=14
      - NUM_WORKERS=5
      - DB_READY=false
    depends_on:
      - redis
      - mempool
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - /d/redis_live:/data
    # docker-compose exec redis redis-cli monitor for logs
    # docker run -it --network some-network --rm redis redis-cli -h some-redis
    # docker run -v /myredis/conf:/usr/local/etc/redis --name myredis redis redis-server /usr/local/etc/redis/redis.conf
  mempool:
    image: ethereum/client-go
    command:
      - --txpool.globalslots=30000
      - --maxpeers=250
      - --http
      - --http.port=8547
      - --http.api="eth,txpool,net,web3"
    volumes:
      - /d/ethereum:/root
    ports:
      - "8547:8547"
      - "30303:30303"
    # docker run --name eth_node -d -p 8547:8547 -v /d/ethereum:/root \
    # ethereum/client-go --http --http.port 8547 \
    #--http.api "eth,txpool,net,web3" --maxpeers 250 --txpool.globalslots 30000
