version: '3'
# todo 
services:
  bot:
    image: bot:0.1
    build: ./bot
    ports:
      - "5000:5000"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      - API_ENDPOINT=http://api:5000/api/
    volumes:
      - ./www:/var/www/html
