version: '3'

services:
  bot:
    image: bot:0.1
    build: .
    environment:
      - REDIS_ENDPOINT=redis://redis:6379/
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
      - REDIS_TEST_PORT=6380
      # - BOT_ADDR=0x0
      - PROVIDER_ENDPOINT=http://localhost:8545 
      - RUNNER_ENDPOINT=http://localhost:5000
      - RUNNER_PORT=5000
      - NODE_ENV=development
      - IPC_PROVIDER_ENDPOINT=/root/.ethereum/geth.ipc
      - WS_PROVIDER_ENDPOINT=ws://localhost:8546
    depends_on:
      - redis
      - mempool
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    # try using docker-compose exec redis redis-cli monitor for logs 
  mempool:
    image: ethereum/client-go
    command: 
      - --txpool.globalslots=75000
      - --maxpeers=250
      - --ws 
      - --ws.api 
      - --eth,txpool,net,web3
    # volumes: 
    #   - d/ethereum:/root
    ports:
      - "8545:8545" 
      - "30303:30303"


